In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [13]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [23]:
ps=10
if ps>8:
    print("valid ps: welcome")
elif ps<8:
    print("invalid ps:ps shold be 8 characters")
else:
    print("please enter your ps to login")

valid ps: welcome


In [27]:
def func(a,b,c):
    print("this is function",a,b,c)
func(1,2,3)    

this is function 1 2 3


In [1]:
#initial place holders
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
import numpy as np
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
import numpy as np
np.arange(20,30,3)


array([20, 23, 26, 29])

In [23]:
import numpy as np
np.linspace(10,30,4)

array([10.        , 16.66666667, 23.33333333, 30.        ])

In [27]:
import numpy as np
np.full((8),9)

array([9, 9, 9, 9, 9, 9, 9, 9])

In [35]:
import numpy as np
e=np.full((3,3),9)
print(e)
print(e.ndim)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
2


In [33]:
import numpy as np
np.full((4,4,3),9)

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

In [55]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.random.random((3,4))

array([[0.08623431, 0.93372603, 0.97835424, 0.77483407],
       [0.80304941, 0.17309932, 0.95120834, 0.44211058],
       [0.82646677, 0.91420459, 0.16370141, 0.25143043]])

In [65]:
import numpy as np
arr=np.array([[4,6,7,8],
             [4,6,9,3],
             [2,6,4,8]])
print(arr.size)


12


In [71]:
arr=np.array([[4,6,7,8],
              [4,6,9,3],
              [2,6,4,8],
              [4,6,7,8],
              [4,6,9,3],
              [2,6,4,8]])
len(arr)


6